# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: lacert.ai
email: alexis.hoffmann@lacert.ai
description: >- # this means to ignore newlines until "baseurl:"
  Lacert.ai est un projet d'aide à la documentation des sinistres fissures. 
  En centralisant une multitude de données telles que des photos des sinistres ou 
  des données météorologiques et géologiques, nous offrons aux collectivités 
  des solutions simples et précises de cartographie pour recenser les sinistres sécheresses 
  survenus dans des communes et justifier l'état de catastrophe naturelle.
baseurl: "/website.lacert.ai" # the subpath of your site, e.g. /blog
domain: r3b3-888.github.io
url: "https://r3b3-888.github.io/website.lacert.ai" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  r3b3-888

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - vendor
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
